-- 코드를 작성해주세요
SELECT A.ID, IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN 
(SELECT PARENT_ID AS ID, COUNT(ID) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID) B USING (ID)
ORDER BY ID
