-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * SALES_AMOUNT AS SALES
FROM PRODUCT
JOIN
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) A
USING (PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE