-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, P.CAR_TYPE, CEIL((C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID AND
H.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-11' AND DATE_FORMAT(END_DATE, '%Y-%m') >= '2022-11'
) 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = C.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
AND (C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 2000000 
WHERE C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV'
ORDER BY FEE DESC, C.CAR_TYPE, CAR_ID DESC
