-- 코드를 작성해주세요
WITH RECURSIVE RC AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT S.ID, S.PARENT_ID, RC.GENERATION + 1
    FROM RC JOIN ECOLI_DATA S
    ON RC.ID = S.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM RC
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
