WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL 
    SELECT HOUR + 1 FROM TIME
    WHERE HOUR < 23
)

SELECT HOUR, IFNULL(COUNT, 0) AS COUNT
FROM TIME T
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
     FROM ANIMAL_OUTS
     GROUP BY HOUR) A
USING (HOUR)
ORDER BY HOUR