-- 코드를 작성해주세요
SELECT DISTINCT EMP_NO, EMP_NAME, 
(
    CASE
        WHEN AVERAGE >= 96 THEN 'S'
        WHEN AVERAGE >= 90 THEN 'A'
        WHEN AVERAGE >= 80 THEN 'B'
        ELSE 'C'
     END
) AS GRADE,
(
    CASE
        WHEN AVERAGE >= 96 THEN SAL * 20 / 100
        WHEN AVERAGE >= 90 THEN SAL * 15 / 100
        WHEN AVERAGE >= 80 THEN SAL * 10 / 100
        ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES E
JOIN
(
    SELECT EMP_NO, (SUM(SCORE) / COUNT(*)) AS AVERAGE
    FROM HR_GRADE
    GROUP BY EMP_NO
) G
USING(EMP_NO)
ORDER BY EMP_NO;