-- 코드를 입력하세요
# SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
# FROM REST_REVIEW 
# JOIN MEMBER_PROFILE
# USING (MEMBER_ID)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (SELECT MEMBER_ID, COUNT(*) AS COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT = 
(SELECT MAX(CNT) AS COUNT
FROM(
SELECT MEMBER_ID, COUNT(*) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID) S)) A
JOIN MEMBER_PROFILE
USING (MEMBER_ID)
JOIN REST_REVIEW
USING (MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT


