-- 코드를 
SELECT B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
LEFT JOIN 
(SELECT ID, PARENT_ID, GENOTYPE FROM ECOLI_DATA) B ON (A.ID = B.PARENT_ID)
WHERE A.GENOTYPE & B.GENOTYPE = A.GENOTYPE
ORDER BY ID