-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE D.SKILL_CODE & (SELECT S.CODE FROM SKILLCODES S WHERE NAME = "PYTHON") >= 1 
OR  D.SKILL_CODE & (SELECT S.CODE FROM SKILLCODES S WHERE NAME = "C#") >= 1
ORDER BY ID