-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MX - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MX 
FROM ECOLI_DATA
GROUP BY YEAR) B
ON (YEAR(A.DIFFERENTIATION_DATE) = B.YEAR)
ORDER BY YEAR, YEAR_DEV