-- 코드를 작성해주세요
SELECT ID, FISH_NAME, A.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
USING (FISH_TYPE)
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) A
USING (FISH_TYPE)
WHERE I.LENGTH = A.LENGTH
ORDER BY ID;