-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A
JOIN 
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) B
USING (FISH_TYPE, LENGTH)
JOIN FISH_NAME_INFO C
USING (FISH_TYPE)
ORDER BY ID
