-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY = '과자' 
OR CATEGORY = '국' 
OR CATEGORY = '김치'
OR CATEGORY = '식용유'
GROUP BY CATEGORY) B
USING (CATEGORY)
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC