-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO A
JOIN (SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVE
FROM FISH_INFO
GROUP BY FISH_TYPE) B
USING (FISH_TYPE)
WHERE AVE >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE